- name: Test Ansible ec2 modules to destroy infrastructure
  connection: local
  hosts: localhost
  vars_files:
  - vars.yml
  tasks:
  - name: Delete subnets
    ec2_vpc_subnet:
      cidr: "{{ item.cidr }}"
      region: "{{ item.zone | regex_replace('[a-z]$') }}"
      state: absent
      vpc_id: "{{ vpc_id }}"
    with_items: "{{ subnet_list }}"
