- name: Test Ansible ec2 modules to destroy infrastructure
  connection: local
  hosts: localhost
  vars_files:
  - vars.yml
  tasks:
  - name: Delete subnets
    ec2_vpc_subnet:
      cidr: "{{ item.cidr }}"
      region: "{{ region }}"
      state: absent
      vpc_id: "{{ vpc_id }}"
    with_items: "{{ subnet_list }}"

  - name: Delete security group
    ec2_group:
      name: allow_local_and_ssh
      region: "{{ region }}"
      state: absent
