- name: Install MySQL server and Kafka connector
  hosts: all
  gather_facts: no
  tasks:
  - name: Wait for server
    wait_for_connection:
      timeout: 360
    become: no

  - name: Install packages
    yum:
      name:
      - net-tools
      - mariadb-server

  - name: Put MySQL config
    copy:
      src: server.cnf
      dest: /etc/my.cnf.d/
    register: my_cnf

  - name: Start MySQL service
    service:
      name: mariadb
      enabled: yes
      state: "{{ 'restarted' if my_cnf.changed else 'started' }}"
