- name: Install MySQL server
  become: yes
  hosts: all
  gather_facts: no
  vars_files:
  - variables.yml
  tasks:
  - name: Wait for server
    wait_for_connection:
      timeout: 360
    become: no

  - name: Install packages
    yum:
      name:
      - net-tools
      - mariadb-server
      - MySQL-python

  - name: Put MySQL config
    template:
      src: server.cnf.j2
      dest: /etc/my.cnf.d/server.cnf
    register: my_cnf

  - name: Start MySQL service
    service:
      name: mariadb
      enabled: yes
      state: "{{ 'restarted' if my_cnf.changed else 'started' }}"

  - name: Add connector user
    mysql_user:
      login_user: root
      name: "{{ connector_user }}"
      host: '%'
      password: "{{ connector_pass }}"
      priv: '*.*:SELECT,RELOAD,SHOW DATABASES,REPLICATION SLAVE,REPLICATION CLIENT'

  - name: Add sink and src databases
    mysql_db:
      login_user: root
      name: "{{ item }}"
    with_items:
    - "{{ sink_database }}"
    - "{{ src_database }}"

  - name: Add sink user
    mysql_user:
      login_user: root
      name: "{{ sink_user }}"
      host: '%'
      password: "{{ sink_pass }}"
      priv: "{{ sink_database }}.*:ALL"

  - name: Add src user
    mysql_user:
      login_user: root
      name: "{{ src_user }}"
      host: '%'
      password: "{{ src_pass }}"
      priv: "{{ src_database }}.*:SELECT"
