- name: Install RabbitMQ server
  become: yes
  hosts: all
  gather_facts: no
  vars_files:
  - variables.yml
  tasks:
  - name: Wait for server
    wait_for_connection:
      timeout: 360
    become: no

  - name: Install erlang
    yum:
      name: https://packagecloud.io/rabbitmq/erlang/packages/el/7/erlang-21.3.2-1.el7.x86_64.rpm/download.rpm

  - name: Add bintray repository
    copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/

  - name: Install packages
    yum:
      name:
      - net-tools
      - rabbitmq-server

  - name: Start rabbitmq server
    service:
      name: rabbitmq-server
      enabled: yes
      state: started

  - name: List rabbitmq users
    shell: "rabbitmqctl -q list_users | awk '{print $1}'"
    register: users_list

  - block:
    - name: Add connector user
      command: "rabbitmqctl add_user {{ connector_user }} {{ connector_pass }}"

    - name: Set permissions for connector user
      command: "rabbitmqctl set_permissions {{ connector_user }} .* .* .*"
    when: connector_user not in users_list.stdout_lines

  - name: Install pip
    easy_install:
      name: pip

  - name: Install pika
    pip:
      name: pika

  - name: Add test scripts
    copy:
      src: "rmq_{{ item }}.py"
      dest: /usr/local/bin/
      mode: 0755
    with_items:
    - send
    - receive
