- name: Install MQTT sink connector
  hosts: all
  gather_facts: no
  vars_files:
  - variables.yml
  vars:
    my_conn_name: mqtt_sink02
    my_conn_url: "{{ connector_url }}/{{ my_conn_name }}"
  tasks:
  - name: Get list of installed connectors
    uri:
      url: "{{ connector_url }}"
      return_content: yes
      validate_certs: no
    register: conn_response

  - name: Parse connectors list
    set_fact:
      conn_list: "{{ conn_response.content | from_json }}"

  - name: Delete existing connector
    uri:
      url: "{{ my_conn_url }}"
      method: DELETE
      status_code: 204
      validate_certs: no
    when: my_conn_name in conn_list

  - name: Add source connector
    uri:
      url: "{{ connector_url }}"
      body:
        name: "{{ my_conn_name }}"
        config:
          connector.class: com.datamountaineer.streamreactor.connect.mqtt.sink.MqttSinkConnector
          connect.mqtt.clean: true
          connect.mqtt.timeout: 1000
          connect.mqtt.keep.alive: 1000
          connect.mqtt.converter.throw.on.error: true
          connect.mqtt.hosts: "tcp://{{ inventory_hostname }}:1883"
          connect.mqtt.username: "{{ connector_user }}"
          connect.mqtt.password: "{{ connector_pass }}"
          connect.mqtt.service.quality: 1
          connect.mqtt.kcql: INSERT INTO /mqtt_sink03 SELECT * FROM mqtt_sink04
          key.converter: org.apache.kafka.connect.json.JsonConverter
          key.converter.schemas.enable: false
          tasks.max: 1
          topics: mqtt_sink04
          value.converter: org.apache.kafka.connect.json.JsonConverter
          value.converter.schemas.enable: false
      body_format: json
      method: POST
      status_code: 201
      validate_certs: no
